// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUfvk-SeP5fRdiqY5AxCV8C2wL9avSIjs',
    appId: '1:290198064276:web:dc987f112a735a61263881',
    messagingSenderId: '290198064276',
    projectId: 'alu-launchpad',
    authDomain: 'alu-launchpad.firebaseapp.com',
    storageBucket: 'alu-launchpad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwBgjuA0HYit21hhQ-9ow4obKFoGrRlOc',
    appId: '1:290198064276:android:9753b9625baedef8263881',
    messagingSenderId: '290198064276',
    projectId: 'alu-launchpad',
    storageBucket: 'alu-launchpad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZeQX4qNY2KPZ_CMejYA8lo9PWERfwtUA',
    appId: '1:290198064276:ios:d37ea355045136b1263881',
    messagingSenderId: '290198064276',
    projectId: 'alu-launchpad',
    storageBucket: 'alu-launchpad.firebasestorage.app',
    iosBundleId: 'com.example.aluLaunchpad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZeQX4qNY2KPZ_CMejYA8lo9PWERfwtUA',
    appId: '1:290198064276:ios:d37ea355045136b1263881',
    messagingSenderId: '290198064276',
    projectId: 'alu-launchpad',
    storageBucket: 'alu-launchpad.firebasestorage.app',
    iosBundleId: 'com.example.aluLaunchpad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUfvk-SeP5fRdiqY5AxCV8C2wL9avSIjs',
    appId: '1:290198064276:web:7cf47b4ad0a0c8f1263881',
    messagingSenderId: '290198064276',
    projectId: 'alu-launchpad',
    authDomain: 'alu-launchpad.firebaseapp.com',
    storageBucket: 'alu-launchpad.firebasestorage.app',
  );
}
